# Generated by Django 4.2.29 on 2026-04-19 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_cafe_closes_at_cafe_opens_at_review_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('emoji', models.CharField(blank=True, max_length=8)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='cafe',
            name='moods',
            field=models.ManyToManyField(blank=True, related_name='cafes', to='api.mood'),
        ),
    ]
