# Generated by Django 4.2.29 on 2026-04-19 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_mood_cafe_moods'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('emoji', models.CharField(blank=True, max_length=8)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('rule_type', models.CharField(choices=[('reservations', 'Reservations count'), ('reviews', 'Reviews count'), ('categories', 'Distinct categories visited'), ('favorites', 'Favorites count')], max_length=20)),
                ('threshold', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['threshold', 'name'],
            },
        ),
    ]
